### ISSUE TITLE
IOS Build fail

### ISSUE THREAD

**Issue by ashleebeggs** [glockio/react-native-counter#1]
Hello, I downloaded the zip package and open in xcode 7.2.1 hit run to build the app, and it fails throwing the error RTCRootView.h file not found... Help
<img width="289" alt="screen shot 2016-03-14 at 8 26 57 pm" src="https://cloud.githubusercontent.com/assets/5018359/13766918/3798458c-ea23-11e5-9536-015b1546d1a0.png">

**Comment by glockio** [comment]
You need to install the project dependencies first. Run   `npm install` in the root dir of the project and let me know if that works :)
